//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recetas_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ROLINTERNACIONAL : ROLORIGEN
    {
        [Key]
        public int IDROLINTERNACIONAL { get; set; }
        //public int IDRECETA { get; set; }
        public string REGION { get; set; }

        public ROLINTERNACIONAL()
        { }

        public ROLINTERNACIONAL(int id, int idReceta, string region)
        {
            this.IDROLINTERNACIONAL = id;
            this.IDRECETA = idReceta;
            this.REGION = region;
        }
    }
}
