//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recetas_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ROLNACIONAL: ROLORIGEN
    {
        [Key]
        public int IDROLNACIONAL { get; set; }
        //public int IDRECETA { get; set; }
        public string PROVINCIA { get; set; }

        public ROLNACIONAL()
        { }

        public ROLNACIONAL(int id, int idReceta, string provincia)
        {
            this.IDROLNACIONAL = id;
            this.IDRECETA = idReceta;
            this.PROVINCIA = provincia;
        }
    }
}
